# Generated by Django 6.1 on 2026-09-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(related_name='watchlists', to='stocks.stock'),
        ),
    ]
