# Generated by Django 6.1 on 2026-09-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
